name: Run Preprocessing Pipeline

on:
  push:
    branches: [main] # Ganti dengan nama branch kamu kalau bukan `main`

jobs:
  run-preprocessing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Sesuaikan dengan versi Python kamu

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Preprocessing Script
        env:
          INPUT_FILE: heart-failure-prediction/heart.csv
          OUTPUT_DIRECTORY: preprocessing/
        run: |
          python preprocessing/automate_Muhammad_Rizki.py

      - name: Upload Processed Files (Optional)
        uses: actions/upload-artifact@v3
        with:
          name: processed-data
          path: preprocessing/
