name: Run Preprocessing Pipeline

on:
  push:
    branches: [main]

jobs:
  run-preprocessing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install python-dotenv  # jika kamu pakai dotenv

      - name: Run Preprocessing Script
        env:
          INPUT_FILE: heart-failure-prediction/heart.csv
          OUTPUT_DIRECTORY: preprocessing/
        run: python preprocessing/automate_Muhammad_Rizki.py

      - name: Upload Preprocessed CSVs as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: preprocessed-csvs
          path: |
            preprocessing/X_train_processed.csv
            preprocessing/X_test_processed.csv
            preprocessing/y_train_processed.csv
            preprocessing/y_test_processed.csv
