name: Run Preprocessing Pipeline

on:
  push:
    branches: [main] # Jalankan saat ada push ke branch 'main'

jobs:
  run-preprocessing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Ubah jika kamu pakai versi Python lain

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Preprocessing Script
        env:
          INPUT_FILE: heart-failure-prediction/heart.csv
          OUTPUT_DIRECTORY: preprocessing/
        run: |
          python preprocessing/automate_Muhammad_Rizki.py

      - name: Commit processed data to repo
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add preprocessing/
          git commit -m "Add processed data [auto]" || echo "No changes to commit"
          git push origin main
